name: rdgen-windows
on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Toolchain check
        shell: pwsh
        run: |
          whoami
          python --version
          git --version
          rustc -V
          cargo -V
          cmake --version
          ninja --version
          flutter --version
          flutter doctor -v
